In [1]:
import numpy as np

In [3]:
l1 = [1,2,3,4]

In [7]:
n1 = np.array(l1)

In [9]:
n1

array([1, 2, 3, 4])

In [11]:
type(n1)

numpy.ndarray

In [15]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [17]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [19]:
type(n2)

numpy.ndarray

In [23]:
n2 = np.zeros((1,2))

In [25]:
n2

array([[0., 0.]])

In [27]:
n2 = np.zeros((5,5))

In [29]:
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
type(n2)

numpy.ndarray

In [33]:
n3 = np.full((2,2),10)

In [35]:
n3

array([[10, 10],
       [10, 10]])

In [37]:
n4 = np.arange(10,20)

In [39]:
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
n4 = np.arange(10,50,5)

In [47]:
n4

array([10, 15, 20, 25, 30, 35, 40, 45])

In [57]:
np.random.randint(100,200,10)

array([130, 159, 194, 174, 154, 182, 160, 177, 168, 166])

In [59]:
n5 = np.array([[1,2,3,4],[4,3,2,1]])

In [61]:
n5

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [65]:
n5.shape = (4,2)

In [67]:
n5

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [69]:
n5.shape = (8,1)

In [71]:
n5

array([[1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1]])

In [102]:
n6 = np.array([10,20,30,40])
n7 = np.array([1,2,3,4])

In [104]:
np.vstack((n6,n7))

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [106]:
np.hstack((n6,n7))

array([10, 20, 30, 40,  1,  2,  3,  4])

In [108]:
np.column_stack((n6,n7))

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [124]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90,100])

In [126]:
np.intersect1d(n1,n2)

array([50, 60])

In [128]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [130]:
np.setdiff1d(n2,n1)

array([ 70,  80,  90, 100])

In [132]:
np.sum([n1,n2])

660

In [134]:
np.sum(n1)

210

In [136]:
np.sum([n1,n2],axis = 1)

array([210, 450])

In [138]:
np.sum([n1,n2],axis = 0)

array([ 60,  80, 100, 120, 140, 160])

In [140]:
n1+1

array([11, 21, 31, 41, 51, 61])

In [142]:
n1

array([10, 20, 30, 40, 50, 60])

In [144]:
n1*2

array([ 20,  40,  60,  80, 100, 120])

In [146]:
n1/5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [148]:
n1-5

array([ 5, 15, 25, 35, 45, 55])

In [150]:
#Mean, Median, Standard Deviation

In [160]:
n1 = np.random.randint(1,50,5)

In [162]:
n1

array([ 7,  7, 12, 48, 15])

In [164]:
np.mean(n1)

17.8

In [166]:
np.median(n1)

12.0

In [168]:
np.std(n1)

15.406492138056604

In [172]:
np.std([1,48]) 

23.5

In [174]:
# to save and load a numpy array

In [176]:
n1

array([ 7,  7, 12, 48, 15])

In [180]:
np.save('my_numpy',n1)

In [182]:
n2 = np.load('my_numpy.npy')

In [184]:
n2

array([ 7,  7, 12, 48, 15])